//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupMake
    {
        public BackupMake()
        {
            this.Components = new HashSet<BackupComponent>();
            this.Models = new HashSet<BackupModel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BackupComponent> Components { get; set; }
        public virtual ICollection<BackupModel> Models { get; set; }
    }
}
