//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupComponent
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string LeaseTag { get; set; }
        public string OrderNumber { get; set; }
        public string MAC { get; set; }
        public bool InstallSoftware { get; set; }
        public bool InstallHardware { get; set; }
        public string Note { get; set; }
        public bool Renewal { get; set; }
        public Nullable<int> MakeId { get; set; }
        public Nullable<int> SignatureId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> SystemGroupId { get; set; }
        public string Damages { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual BackupMake Make { get; set; }
        public virtual BackupModel Model { get; set; }
    }
}
