//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charge
    {
        public Charge()
        {
            this.Leases = new HashSet<Lease>();
        }
    
        public int Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> VendorRateId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> TaxId { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual VendorRate VendorRate { get; set; }
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
