//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coordinator
    {
        public Coordinator()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int Id { get; set; }
        public string GID { get; set; }
        public bool BillingAccess { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
    }
}
