//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Leases = new HashSet<Lease>();
            this.Coordinators = new HashSet<Coordinator>();
            this.SingleCharges = new HashSet<SingleCharge>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Fund { get; set; }
        public string Org { get; set; }
        public string Program { get; set; }
    
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual ICollection<Coordinator> Coordinators { get; set; }
        public virtual ICollection<SingleCharge> SingleCharges { get; set; }
    }
}
