//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptContactInfo
    {
        public string BILL_LEVEL_CODE { get; set; }
        public string BILL_LEVEL_DSC { get; set; }
        public string BILL_Desc { get; set; }
        public string BILL_Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Fund { get; set; }
        public string Org { get; set; }
        public string Program { get; set; }
        public int RecordID { get; set; }
    }
}
