//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public int Id { get; set; }
        public string HTML { get; set; }
        public int SystemGroup_Id { get; set; }
    
        public virtual SystemGroup SystemGroup { get; set; }
    }
}
