//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewOrdersPending
    {
        public int RecordID { get; set; }
        public string SerialNumber { get; set; }
        public string SR { get; set; }
        public string LeaseTag { get; set; }
        public string Fund { get; set; }
        public string Org { get; set; }
        public string Program { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StatementName { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Component { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Component2 { get; set; }
        public string LeaseTag2 { get; set; }
        public string SerialNumber2 { get; set; }
        public string Manufacturer2 { get; set; }
        public string Model2 { get; set; }
        public string Component3 { get; set; }
        public string LeaseTag3 { get; set; }
        public string SerialNumber3 { get; set; }
        public string Manufacturer3 { get; set; }
        public string Model3 { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Maintenance { get; set; }
        public string OrderNumber { get; set; }
        public string ContractNumber { get; set; }
        public string ParentTag { get; set; }
        public string OrdererUserName { get; set; }
        public string OrdererFirstName { get; set; }
        public string OrdererLastName { get; set; }
        public string OrdererPhone { get; set; }
        public string OrdererEmail { get; set; }
        public string OrdererDepartment { get; set; }
        public Nullable<bool> Renewal { get; set; }
        public Nullable<int> Term { get; set; }
        public string RateLevel { get; set; }
        public Nullable<bool> LabOrder { get; set; }
        public string LabName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Scanned { get; set; }
        public Nullable<System.DateTime> Prepped { get; set; }
        public Nullable<int> MonitorCount { get; set; }
        public Nullable<decimal> Reference { get; set; }
        public Nullable<bool> Finalized { get; set; }
        public string EOLSerial { get; set; }
        public string EOLTag { get; set; }
        public string EOLSerial2 { get; set; }
        public string EOLTag2 { get; set; }
        public string EOLSerial3 { get; set; }
        public string EOLTag3 { get; set; }
        public string OldSerial { get; set; }
        public bool Cancelled { get; set; }
        public string OperatingSystem { get; set; }
        public Nullable<bool> Rate { get; set; }
    }
}
