//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabaseMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewUserInfo
    {
        public string SerialNumber { get; set; }
        public string SR { get; set; }
        public string LeaseTag { get; set; }
        public string Component { get; set; }
        public string Fund { get; set; }
        public string Org { get; set; }
        public string Program { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string UserID { get; set; }
        public string Notes { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<bool> Maintenance { get; set; }
        public string OrderNumber { get; set; }
        public string ContractNumber { get; set; }
        public string ParentTag { get; set; }
        public string BeginBillDate { get; set; }
        public string EndBillDate { get; set; }
        public Nullable<decimal> MonthlyCharge { get; set; }
        public string EOLSerial { get; set; }
        public string EOLTag { get; set; }
        public string OldSerial { get; set; }
        public string RateLevel { get; set; }
        public string StatementName { get; set; }
    }
}
