//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeasingDatabaseMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OldAuleaseEntities : DbContext
    {
        public OldAuleaseEntities()
            : base("name=OldAuleaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Billing> Billings { get; set; }
        public DbSet<DeptContactInfo> DeptContactInfoes { get; set; }
        public DbSet<NewUserInfo> NewUserInfoes { get; set; }
        public DbSet<NewOrdersPending> NewOrdersPendings { get; set; }
    }
}
