//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public PO()
        {
            this.SystemGroups = new HashSet<SystemGroup>();
        }
    
        public int Id { get; set; }
        public string PONumber { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<SystemGroup> SystemGroups { get; set; }
    }
}
