//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.Components = new HashSet<Component>();
            this.StandardComponents = new HashSet<StandardComponent>();
        }
    
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Component> Components { get; set; }
        public virtual ICollection<StandardComponent> StandardComponents { get; set; }
    }
}
