//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardComponent
    {
        public StandardComponent()
        {
            this.Properties = new HashSet<Property>();
            this.StandardOptionStandardComponents = new HashSet<StandardOptionStandardComponent>();
        }
    
        public int Id { get; set; }
        public int ModelId { get; set; }
        public int TypeId { get; set; }
        public int MakeId { get; set; }
    
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Model Model { get; set; }
        public virtual Type Type { get; set; }
        public virtual Make Make { get; set; }
        public virtual ICollection<StandardOptionStandardComponent> StandardOptionStandardComponents { get; set; }
    }
}
