//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardOption
    {
        public StandardOption()
        {
            this.StandardOptionStandardComponents = new HashSet<StandardOptionStandardComponent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal BaseRate24 { get; set; }
        public decimal BaseRate36 { get; set; }
        public decimal SupportRate24 { get; set; }
        public decimal SupportRate36 { get; set; }
    
        public virtual ICollection<StandardOptionStandardComponent> StandardOptionStandardComponents { get; set; }
    }
}
