//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardOptionStandardComponent
    {
        public int Id { get; set; }
        public int StandardOptionId { get; set; }
        public int StandardComponentId { get; set; }
    
        public virtual StandardComponent StandardComponent { get; set; }
        public virtual StandardOption StandardOption { get; set; }
    }
}
