//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemGroup
    {
        public SystemGroup()
        {
            this.Leases = new HashSet<Lease>();
            this.EOLComponents = new HashSet<Component>();
            this.Forms = new HashSet<Form>();
            this.Location = new Location();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> POId { get; set; }
    
        public Location Location { get; set; }
    
        public virtual ICollection<Lease> Leases { get; set; }
        public virtual User User { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<Component> EOLComponents { get; set; }
        public virtual PO PO { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
    }
}
