//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aulease.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Charges = new HashSet<Charge>();
            this.Components = new HashSet<Component>();
            this.StandardComponents = new HashSet<StandardComponent>();
            this.VendorRates = new HashSet<VendorRate>();
            this.Overheads = new HashSet<Overhead>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Charge> Charges { get; set; }
        public virtual ICollection<Component> Components { get; set; }
        public virtual ICollection<StandardComponent> StandardComponents { get; set; }
        public virtual ICollection<VendorRate> VendorRates { get; set; }
        public virtual ICollection<Overhead> Overheads { get; set; }
    }
}
